draw_text(10,10,"timeheld " + string(obj_player.timeheld))
draw_text(10,20,"max " + string(obj_player.maxspeed))
draw_text(10,30,"vspd " + string(obj_player.vspeed))
draw_text(10,40,"hspd " + string(obj_player.hspeed))
draw_text(10,50,"index " + string(obj_player.sprite_index))
draw_text(10,60,"direction " + string(obj_player.direction))
draw_text(10,70,"dir " + string(obj_player.dir))